name: Deploy to Railway

on:
  push:
    branches:
      - main  # Atau branch yang kamu gunakan untuk deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Pastikan kamu sudah menyimpan Railway token di GitHub Secrets
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway up
